FROM node:24.14.0-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

EXPOSE 3000

# ENTRYPOINT npm run dev -- --host 0.0.0.0
# RUN npm run dev -- --host 0.0.0.0
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
